### ISSUE TITLE
Few questions regard the implementation :) 

### ISSUE THREAD

**Issue by RaynDol** [oze4/workerpoolxt#1]
Hi,

Great lib & work!

 
1. To use multiple jobs, should I do it like following?  it will run in concurrent mode when doing like this ? is there a shorter way to write it (like an array )? 

```
	myreactor.Add(reactor.Job{
		Name: "job1",
		Runner: func(c *reactor.Client) reactor.React {
			// do something with client `c`
			res, _ := c.HTTP.Get("xyz.com")
			return reactor.React{Info: res}
		},
	})

	myreactor.Add(reactor.Job{
		Name: "job2",
		Runner: func(c *reactor.Client) reactor.React {
			// do something with client `c`
			res, _ := c.HTTP.Get("xyz.com")
			return reactor.React{Info: res}
		},
	})
```

Thanks!

**Comment by oze4** [comment]
Yes, these jobs are ran concurrently.  The jobs are run as soon as they are submitted but you cannot retrieve results until you call `myreactor.Reactions()`.  After calling `Reactions()` you CANNOT add more jobs.

So to answer your question, it is the same as before.  All jobs run concurrently as soon as they are submitted but results are not retrieved until you call `workerpool.StopWait()`, which is what `Reactions()` ultimately calls.

I have also updated the code and the readme to show how you can add in bulk (although, I don't understand why you would want to do this since when adding one by one the jobs will run right away)...

**Comment by RaynDol** [comment]
Thanks a lot, works perfect! 
1. I see that the timeout is defined in general , is it possible to provide timeout for each job(with your framework) ? 
2. Assume I've multiple request for http, is it possible to reduce the duplicate code (if it simple of course) , which means the job will get only url or list of url and run them ? I mean with the current framework ...

**Comment by oze4** [comment]
What are you considering to be duplicate code? You should be able to integrate context into each request.

**Comment by RaynDol** [comment]
Hi @oze4  

1 . Duplicate code I mean a way to define only list of URL that will run by the job, e.g.  like some http request, e.g. I put an array of 10 url only and it will be run in 10 jobs and each url will be send the response if success or error, is it possible with the current implematation  ?

**Comment by oze4** [comment]
I am confused by this because the original answer I supplied to you nearly a week ago (via StackOverflow) showed you how to do something as simple as that.  Then you asked about being able to do anything inside a job, then you needed to be able to gather job runtime as well as be able to kill jobs after N timeout.

We seem to have come full circle.

You can abstract things however you wish. I have shown you how you can abstract a package (workerpool) to get it to do what you want.

Just apply that same concept here and abstract either this package or `workerpool` package...

Lastly, I suggest you review/study/learn the examples I have provided you over the past week. It will only help YOU if you play with the code as opposed to just asking how to do it.

What have you tried? Have you done anything to try and accomplish your goal?

This pseudo code should get the idea across, but from here on out these types of questions are not "issues". They seem to be related to your understanding of Go.  

I do not mean to come across as rude, I enjoy learning and helping others learn, but that is where the issue lies - it doesn't feel like you are doing anything to learn.  I'll help you all day long but you have to show me you're learning/doing/trying something, otherwise it feels like I'm doing your job (or whatever this code is for) for you.

```golang
package main

import (
	"fmt"
	"time"

	"github.com/oze4/reactor"
)

func main() {
	urlreactor := URLReactor{
		URLS:    []string{"google.com", "yahoo.com"},
		Reactor: reactor.New(10, time.Duration(time.Second*10)),
	}

	results := urlreactor.Do()

	for _, r := range results {
		fmt.Println(r)
	}
}

type URLReactor struct {
	URLS    []string
	Reactor reactor.Reactor
}

func (u *URLReactor) Do() reactor.Reactions {
	if len(u.URLS) <= 0 {
		return reactor.Reactions{}
	}

	for _, url := range u.URLS {
		u.Reactor.React(reactor.NewEvent(url, func(c *reactor.Client) reactor.Reaction {
			resp, err := c.HTTP.Get(url)
			if err != nil {
				return reactor.Reaction{Error: err}
			}
			return reactor.Reaction{Response: resp}
		}))
	}

	return u.Reactor.ReactionsStop()
}
```

**Comment by RaynDol** [comment]
Sorry, I didn't want you to get this impression, most of the time that i've asked a question is when I try something and it doesn't work or it works but I want to get your insights too, as at appear that every time that I write something (which works) you answer with better suggestion/ approach...
Again sorry and I want to say that I learn from you a lot, see where we was one week ago and now. its much more robust and clean and for me it's fairly advanced. Thank you very much sir for your time and help! you are great!

Btw you are right , we did where in place at the beginning of our journey, however if you remember, we want to support both option and full flexibility   again thanks!

**Comment by oze4** [comment]
Ahh that's my fault. You should supply the code you have tried next time! I bet you're on the right path 😄 

Happy to help if you need anything further.

**Comment by RaynDol** [comment]
Thanks sir!

Ive only two issue.
1 . how to add to your example with the url  a name for each job as I need to return the name to know who faild and who succeed (will try it soon - I think it shouldnt be complicated ...)

2. how to provide a timeout for specific job (maybe with some config) . for this im not sure...

**Comment by oze4** [comment]
You can create URL object and use it instead of `URLS: []string` so that it contains a name and a url. My example just used the URL as the name. 

Lastly, you are passing in an http.Client to each job. Http clients allow you to pass in a request via `client.Do(http.Request)`. On each `http.Request` there is a `Timeout` field...Therefore, you can create your own `http.Request` object with whatever Timeout you want inside each job.

**Comment by RaynDol** [comment]
1. Yes, Im working on it.
2. yes can use the http for that but this is specific for http client, in case I have another client like k8s or other this is the issue..

**Comment by oze4** [comment]
I'm not sure I follow. I thought you wanted to just send http requests and allow the user to just supply a url?

**Comment by RaynDol** [comment]
for example, if I run list of http calls (with each url have his specifc timeout ) and in addition some custom jobs, and each job from the list and from custom job(like call to k8s) should have also  specific timeout ...please let me know if its more clear now?

**Comment by oze4** [comment]
Yea that makes sense, which I understood. What I don't understand is you just asked me to give you something so the user only had to supply a URL....

I went ahead and updated this package to allow for timeouts per job. I have not tested any of this, but it *should* work.. 

https://github.com/oze4/reactor/blob/master/reactor.go#L89-L93

**Comment by RaynDol** [comment]
Great! will check it ASAP

**Comment by RaynDol** [comment]
I saw that you change the library, could I ask what was the technical reasons ?

**Comment by oze4** [comment]
I think it is more in line with the library I am abstracting (workerpool).  To me, it makes more sense to keep the abstraction high(er) at this level (i.e. not supplying a client any longer).  Consumers of this package can abstract things like that further out. I don't want to pinhole people by making them import k8's packages when they may not even be using k8s. 

The client example was niche to fit your need, so you'll need to follow the same idea as before and abstract this package so you can supply your own client.
