### ISSUE TITLE
Extend with specific client

### ISSUE THREAD

**Issue by RaynDol** [oze4/workerpoolxt#4]
Hi,

As discuses I open a new question with example of my code.

I need to extend the current implementation with my clients, Im doing that like following:
this works, but am I doing it right ? is there a better/cleaner approach to add those clients / interface in go... ? 
to gain some confidence, i'll appreciate your example also.

Thanks in advance!

```

// Inject worker client
type Client struct {
	HTTP       http.Client
	Kubernetes kubernetes.Clientset
}

type WorkerClients struct {
	client *Client
	wp     *workerpoolxt.WorkerPoolXT
}

func main() {

	wp := workerpoolxt.New(10, time.Duration(time.Second*10))

	aa := WorkerClients{
		client: &Client{
			HTTP:       HTTPClient(),
			Kubernetes: AnotherClient(),
		},
		wp: wp,
	}

	aa.wp.SubmitXT(
		workerpoolxt.Job{ // For demo purposes, this job will timeout
			Name:    "Job1",
			Timeout: time.Second * 5,
			Task: func() workerpoolxt.Response {
				res, e := aa.client.HTTP.Get("http://www.google.com")
				if e != nil {
					return workerpoolxt.Response{Error: e}
				}
				return workerpoolxt.Response{Data: res.StatusCode}
			},
		})

	wp.SubmitXT(
		workerpoolxt.Job{ // For demo purposes, this job will timeout
			Name:    "Job2",
			Timeout: time.Second * 1,
			Task: func() workerpoolxt.Response {
				time.Sleep(time.Second * 2)
				return workerpoolxt.Response{Data: "Hello"}
			},
		})

	// Submit as many jobs as you would like

	results := wp.StopWaitXT()

```

**Comment by oze4** [comment]
That is entirely up to you.

**Comment by RaynDol** [comment]
Yes but may I ask you kindly, does it make sense to use it like this or you think it's ugly way ?

**Comment by oze4** [comment]
I think you should mirror how I showed you prior.

**Comment by RaynDol** [comment]
Not sure that I got it, as before it was part of the library (the client) , how can I "mirror" it with the new implementation  ?

**Comment by oze4** [comment]
You'll have to wrap around this package by creating your own package that follows the logic [from here](https://stackoverflow.com/a/64210733/10431732) (look under the "Code for library" section).. instead of importing workerpool you would import workerpoolxt and use the XT methods (i.e. SubmitXT, StopWaitXT, etc...)

You'll find the way I have coded things still allows you to access methods from workerpool as well. That's why I refactored things.

**Comment by oze4** [comment]
Hey @RaynDol I went ahead and came up with a dynamic way to add clients.  The idea is to supply options as `map[string]interface{}` so that you can provide any options you wish.

- Providing options is optional

 - Options are nothing more than `map[string]interface{}` so that you may supply anything you wish. This also simplifies accessing options within a job.

 - You can supply options along with the workerpool, or on a per job basis. If a job has options set, it overrides the defaults **it does not merge options**.

### Supply default options

```golang
import (
    wpxt "github.com/oze4/workerpoolxt"
    // ...
)

wp := wpxt.New(10, time.Duration(time.Second*10))
myopts := map[string]interface{}{
    "myclient": &http.Client{},
    // "k8s": &kubernetes.Clientset{}
    // etc....
}
wp.WithOptions(myopts)

wp.SubmitXT(wpxt.Job{
    Name: "myjob",
    Task: func(o wpxt.Options) wpxt.Response {
        // access options here
        httpclient := o["myclient"]
        // k8sclient := o["k8s"]
    }, 
})
```

### Supply options per job

```golang
import (
    wpxt "github.com/oze4/workerpoolxt"
    // ...
)

wp := wpxt.New(10, time.Duration(time.Second*10))
myclient := &http.Client{}

wp.SubmitXT(wpxt.Job{
    Name: "myjob",
    Options: map[string]interface{}{
        "http": myclient 
    },
    Task: func(o wpxt.Options) wpxt.Response {
        // access options here
        httpclient := o["http"]
    }, 
})
```
